# @format

version: "4.27"

services:
  mongodb:
    image: mongo:6.0.13
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
